# 1.0 Import

In [19]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

## 1.1 Load Dataset

In [5]:
dataset_path = 'data/train.csv'
df = pd.read_csv(dataset_path)

In [10]:
df.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar

# 2.0 Feature Selection

In [14]:
#x = features_train
#y = label

features = ['idade', 'saldo_atual', 'divida_atual', 'renda_anual',
            'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
            'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
            'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']
label = 'limite_adicional'

x_train = df.loc[:, features]
y_train = df.loc[:, label]

# 3.0 Train

In [26]:
#definção de parametros do treinamento
k = 7
knn_classifier = KNeighborsClassifier(n_neighbors = k)

#treinamento do algoritmo
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [27]:
y_pred = knn_classifier.predict(x_train)

In [28]:
df_result = df.copy()
df_result['classificacao'] = y_pred

In [35]:
df_result.loc[:, ['id_cliente', 'idade', 'limite_adicional', 'classificacao']].sample(10)

      id_cliente  idade limite_adicional classificacao
1689         705     55            Negar         Negar
8055        2776     52            Negar         Negar
5992        4253     59         Conceder         Negar
1946        8762     28         Conceder      Conceder
2840        9878     34            Negar         Negar
3925        8890     60            Negar         Negar
8874        9223     41            Negar         Negar
426         6558     34            Negar         Negar
4844        1006     27            Negar         Negar
7597        8979     48         Conceder      Conceder