# 1.0 Import

In [113]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics as mt

## 1.1 Load Dataset

In [114]:
dataset_path = 'data/train.csv'
df = pd.read_csv(dataset_path)

In [115]:
df.head()

,id_cliente,idade,saldo_atual,divida_atual,renda_anual,valor_em_investimentos,taxa_utilizacao_credito,num_emprestimos,num_contas_bancarias,num_cartoes_credito,dias_atraso_dt_venc,num_pgtos_atrasados,num_consultas_credito,taxa_juros,investe_exterior,pessoa_polit_exp,limite_adicional
0,1767,21,278.172008,2577.05,24196.89636,104.306544,31.038763,6,5,7,21,14,9,15,Não,Não,Negar
1,11920,40,268.874152,2465.39,19227.37796,69.858778,36.917093,5,8,5,40,23,10,18,Não,Não,Negar
2,8910,36,446.643127,1055.29,42822.28223,134.201478,34.561714,0,3,6,26,13,3,15,Sim,Não,Negar
3,4964,58,321.141267,703.05,51786.82600,297.350067,31.493561,0,3,7,12,7,2,1,Sim,Não,Negar
4,10100,35,428.716114,891.29,44626.85346,134.201478,28.028887,2,8,7,24,10,8,20,Sim,Não,Negar

# 2.0 Feature Selection

In [116]:
#x = features_train
#y = label

features = ['idade', 'saldo_atual', 'divida_atual', 'renda_anual',
            'valor_em_investimentos', 'taxa_utilizacao_credito', 'num_emprestimos',
            'num_contas_bancarias', 'num_cartoes_credito', 'dias_atraso_dt_venc',
            'num_pgtos_atrasados', 'num_consultas_credito', 'taxa_juros']
label = 'limite_adicional'

x_train = df.loc[:, features]
y_train = df.loc[:, label]

In [117]:
df.loc[:, 'limite_adicional'].value_counts(normalize = True)

Negar       0.841579
Conceder    0.158421
Name: limite_adicional, dtype: float64

# 3.0 Train

In [129]:
#definção de parametros do treinamento
k = 7
knn_classifier = KNeighborsClassifier(n_neighbors = k)

#treinamento do algoritmo
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [130]:
y_pred = knn_classifier.predict(x_train)

In [131]:
df_result = df.copy()
df_result['classificacao'] = y_pred

In [132]:
df_result.loc[:, ['id_cliente', 'idade', 'limite_adicional', 'classificacao']].sample(10)

      id_cliente  idade limite_adicional classificacao
5049        3251     25            Negar         Negar
6687        9628     29            Negar         Negar
2936        4016     31         Conceder         Negar
6542          29     45            Negar         Negar
8748        6681     60            Negar         Negar
5620       12480     28            Negar         Negar
89          1693     26            Negar         Negar
3791        4396     19            Negar         Negar
5248         414     29            Negar         Negar
475         3955     56            Negar         Negar

In [133]:
df_result['acertos'] = (df_result.loc[:, ['id_cliente', 'limite_adicional', 'classificacao']]
        .apply(lambda x: 1 if x ['limite_adicional'] == x['classificacao'] else 0, axis=1))

# 4.0 Perfomance

## 4.1 Confusion Matrix

In [134]:
mt.confusion_matrix(y_train, y_pred)

array([[ 369, 1136],
       [ 203, 7792]], dtype=int64)

In [135]:
7792 / (7792 + 1136)

0.8727598566308243

## 4.2 Accuracy

In [136]:
mt.accuracy_score (y_train, y_pred)

0.8590526315789474

## 4.3 Precision

In [137]:
mt.precision_score(y_train, y_pred, pos_label='Conceder')

0.6451048951048951

## 4.4 Recall

In [138]:
mt.recall_score (y_train, y_pred, pos_label='Conceder')

0.24518272425249169